import type { Metadata } from "next";
import "@/styles/globals.css";
import { publicSans } from "@/fonts/fonts.google";
import { cn } from "@/lib/utils";
import Providers from "@/providers/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          publicSans.className,
          "h-screen overflow-hidden"
        )}
      >
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
